version: '3'
services:
  webapp:
    build: ./webapp
    ports:
      - 80:80
    volumes:
      - ./data:/var/log/nginx/
  
  monitoring:
    build: ./monitoring
    volumes:
      - ./data:/servlog
